stages:
  - test

variables:
  RUST_BACKTRACE: "FULL"
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential
- apt-get install -yqq --no-install-recommends libgtk-3-dev
- apt-get install -yqq libgmp-dev
# - apt-get install -yqq --no-install-recommends meson

test:stable:
  # Stable img
  # https://hub.docker.com/_/rust/
  image: "rust"
  script:
  - rustc --version && cargo --version
  - cd fractal-gtk/res/ && glib-compile-resources --generate resources.xml && cd ../../
  - cargo build --all
  - cargo test --all --verbose
  cache:
      paths:
        - target/
        - cargo/

test:nightly:
  # Nightly
  # https://hub.docker.com/r/rustlang/rust/
  image: "rustlang/rust:nightly"
  script:
  - rustc --version && cargo --version
  - cd fractal-gtk/res/ && glib-compile-resources --generate resources.xml && cd ../../
  - cargo build --all
  - cargo test --all --verbose
  # - cargo bench
  cache:
      paths:
        - target/
        - cargo/

