[package]
authors = ["Jonas Platte <mail@jonasplatte.de>"]
name = "ruma-gtk"
version = "0.1.0"

[dependencies]
gio = "0.1.1"
reqwest = "0.2.0"

[dependencies.gtk]
features = ["v3_12"]
version = "0.1.1"

[dependencies.ruma-client-api]
git = "https://github.com/ruma/ruma-client-api"
