[package]
authors = ["Daniel Garcia <danigm@wadobo.com>"]
name = "guillotine"
version = "0.1.0"

[dependencies]
gio = "0.1.3"
reqwest = "0.7.2"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_json = "1.0.2"
url = "1.5.1"

[dependencies.gtk]
features = ["v3_12"]
version = "0.1.3"
