[package]
authors = ["Daniel Garcia <danigm@wadobo.com>"]
build = "build.rs"
name = "fractal-gtk"
version = "0.1.3"
workspace = "../"

[dependencies]
gdk = "0.7.0"
gdk-pixbuf = "0.3.0"
gdk-pixbuf-sys = "0.5.0"
gio = "0.3.0"
glib = "0.4.0"
mime = "0.3.5"
notify-rust = "3.4.2"
pango = "0.3.0"
regex = "0.2.3"
reqwest = "0.8.1"
secret-service = "0.4.0"
serde = "1.0.23"
serde_derive = "1.0.23"
serde_json = "1.0.6"
time = "0.1.38"
tree_magic = "0.2.0"
url = "1.6.0"

[dependencies.cairo-rs]
features = ["png"]
version = "0.3.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.gtk]
features = ["v3_22"]
version = "0.3.0"
